name: my-check
on: push
jobs:
  linter_and_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install poetry
      run: pip install poetry
    - name: install dependencies
      run: poetry install
    - name: run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: poetry run python manage.py test
    - name: run linter
      run: poetry run flake8 .